import os
from datetime import datetime
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[2]
REPORTS_DIR = ROOT_DIR / "reports"


def get_ai_mode_label() -> str:
    """Return a human-readable AI mode label for report traceability."""
    offline_mode = os.getenv("SPROUT_OFFLINE_MODE", "false").lower() == "true"
    if offline_mode:
        return "Offline fallback"
    return "Gemini live with fallback"


def create_review_header(package_data: dict[str, Any]) -> str:
    """Create a standard human-review header for generated outputs."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    client_name = package_data.get("client_name", "Unknown Client")
    reporting_month = package_data.get("reporting_month", "Unknown Period")
    package_type = package_data.get("package_type", "Monthly Board Package")
    model_name = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")

    return f"""---
Generated by: SproutAgent
Workflow: {package_type}
Output type: Draft for human review
Client: {client_name}
Reporting period: {reporting_month}
AI mode: {get_ai_mode_label()}
Configured model: {model_name}
Source data: Mock monthly board package data
Generated at: {generated_at}
---

## Source Data Context

This report was generated from structured mock CFO/FP&A data, including budget, actuals, forecast, prior month actuals, KPI values, cost drivers, leadership notes, and risk indicators.

"""


def save_monthly_board_package(
    package_data: dict[str, Any],
    narrative_markdown: str,
) -> Path:
    """Save the Monthly Board Package draft as Markdown."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    client_slug = package_data.get("client_name", "client").lower().replace(" ", "-")
    reporting_month = package_data.get("reporting_month", "period")
    output_path = REPORTS_DIR / f"{reporting_month}-{client_slug}-monthly-board-package.md"

    final_markdown = create_review_header(package_data) + narrative_markdown
    output_path.write_text(final_markdown, encoding="utf-8")
    return output_path
