from datetime import datetime
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[2]
REPORTS_DIR = ROOT_DIR / "reports"


def create_review_header(package_data: dict[str, Any]) -> str:
    """Create a standard human-review header for generated outputs."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    client_name = package_data.get("client_name", "Unknown Client")
    reporting_month = package_data.get("reporting_month", "Unknown Period")

    return f"""---
Generated by: SproutAgent
Output type: Draft for human review
Client: {client_name}
Reporting period: {reporting_month}
Generated at: {generated_at}
---

"""


def save_monthly_board_package(
    package_data: dict[str, Any],
    narrative_markdown: str,
) -> Path:
    """Save the Monthly Board Package draft as Markdown."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    client_slug = package_data.get("client_name", "client").lower().replace(" ", "-")
    reporting_month = package_data.get("reporting_month", "period")
    output_path = REPORTS_DIR / f"{reporting_month}-{client_slug}-monthly-board-package.md"

    final_markdown = create_review_header(package_data) + narrative_markdown
    output_path.write_text(final_markdown, encoding="utf-8")
    return output_path
